"""
Aider AI 代码智能体服务
基于 Aider AI (https://github.com/Aider-AI/aider) 的代码生成和编辑服务
"""

import os
import json
import subprocess
import tempfile
from typing import Dict, List, Optional
from pathlib import Path


class AiderService:
    """Aider AI 服务类"""
    
    def __init__(self, api_key: Optional[str] = None, model: str = "deepseek"):
        """
        初始化 Aider 服务
        
        Args:
            api_key: DeepSeek API密钥（如果不提供，将从环境变量读取）
            model: 使用的模型，默认为 deepseek
        """
        self.api_key = api_key or os.environ.get('DEEPSEEK_API_KEY')
        self.model = model
        self.work_dir = Path(tempfile.mkdtemp(prefix='aider_'))

    def _run_aider(self, args: List[str], timeout: int = 120) -> subprocess.CompletedProcess:
        env = os.environ.copy()
        if os.name == "nt":
            command_line = subprocess.list2cmdline(args)
            cmd = ["cmd.exe", "/c", command_line]
        else:
            cmd = args
        return subprocess.run(
            cmd,
            cwd=self.work_dir,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout
        )
        
    def generate_code(self, prompt: str, language: str = "python", 
                     context_files: Optional[List[str]] = None) -> Dict:
        """
        生成代码
        
        Args:
            prompt: 用户的代码需求描述
            language: 编程语言
            context_files: 上下文文件列表
            
        Returns:
            包含生成的代码文件和响应消息的字典
        """
        try:
            # 准备 Aider 命令
            cmd = [
                'aider',
                '--yes',  # 自动确认
                '--no-git',  # 不使用 git
                f'--model={self.model}',
            ]
            
            # 添加 DeepSeek API key
            if self.api_key:
                cmd.extend(['--api-key', f'deepseek={self.api_key}'])
            
            # 添加消息
            cmd.extend(['--message', prompt])
            
            # 如果有上下文文件，添加到命令中
            if context_files:
                cmd.extend(context_files)
            
            # 设置环境变量
            result = self._run_aider(cmd, timeout=120)
            
            # 收集生成的文件
            generated_files = self._collect_generated_files()
            
            # 如果没有生成文件，返回错误信息以便前端使用后备方案
            if not generated_files:
                return {
                    'success': True,
                    'message': 'Aider 执行完成，但未生成文件（前端将使用模拟文件）',
                    'files': [],
                    'output': result.stdout,
                    'language': language,
                    'note': 'No files generated by Aider'
                }
            
            return {
                'success': True,
                'message': '代码生成成功',
                'files': generated_files,
                'output': result.stdout,
                'language': language
            }
            
        except subprocess.TimeoutExpired:
            return {
                'success': False,
                'message': '代码生成超时，请简化需求或稍后重试',
                'files': [],
                'error': 'timeout'
            }
        except Exception as e:
            return {
                'success': False,
                'message': f'代码生成失败: {str(e)}',
                'files': [],
                'error': str(e)
            }
    
    def edit_code(self, file_path: str, edit_prompt: str) -> Dict:
        """
        编辑现有代码
        
        Args:
            file_path: 要编辑的文件路径
            edit_prompt: 编辑指令
            
        Returns:
            包含编辑结果的字典
        """
        try:
            cmd = [
                'aider',
                '--yes',
                '--no-git',
                f'--model={self.model}',
            ]
            
            # 添加 DeepSeek API key
            if self.api_key:
                cmd.extend(['--api-key', f'deepseek={self.api_key}'])
            
            # 添加消息和文件
            cmd.extend(['--message', edit_prompt, file_path])
            
            result = self._run_aider(cmd, timeout=120)
            
            # 读取编辑后的文件
            edited_file = self.work_dir / file_path
            if edited_file.exists():
                with open(edited_file, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                return {
                    'success': True,
                    'message': '代码编辑成功',
                    'file': {
                        'path': file_path,
                        'content': content
                    },
                    'output': result.stdout
                }
            else:
                return {
                    'success': False,
                    'message': '编辑后的文件未找到',
                    'error': 'file_not_found'
                }
                
        except Exception as e:
            return {
                'success': False,
                'message': f'代码编辑失败: {str(e)}',
                'error': str(e)
            }
    
    def explain_code(self, code: str, language: str = "python") -> Dict:
        """
        解释代码
        
        Args:
            code: 要解释的代码
            language: 编程语言
            
        Returns:
            包含代码解释的字典
        """
        # 创建临时文件
        temp_file = self.work_dir / f"temp.{self._get_file_extension(language)}"
        with open(temp_file, 'w', encoding='utf-8') as f:
            f.write(code)
        
        prompt = "请详细解释这段代码的功能、逻辑和关键部分。"
        
        try:
            cmd = [
                'aider',
                '--yes',
                '--no-git',
                f'--model={self.model}',
            ]
            
            # 添加 DeepSeek API key
            if self.api_key:
                cmd.extend(['--api-key', f'deepseek={self.api_key}'])
            
            # 添加消息和文件
            cmd.extend(['--message', prompt, str(temp_file)])
            
            result = self._run_aider(cmd, timeout=60)
            
            return {
                'success': True,
                'explanation': result.stdout,
                'language': language
            }
            
        except Exception as e:
            return {
                'success': False,
                'message': f'代码解释失败: {str(e)}',
                'error': str(e)
            }
    
    def _collect_generated_files(self) -> List[Dict]:
        """收集生成的文件"""
        files = []
        for file_path in self.work_dir.rglob('*'):
            if file_path.is_file() and not file_path.name.startswith('.'):
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    files.append({
                        'name': file_path.name,
                        'path': str(file_path.relative_to(self.work_dir)),
                        'content': content,
                        'size': self._format_file_size(file_path.stat().st_size),
                        'type': self._get_file_type(file_path.suffix)
                    })
                except Exception as e:
                    print(f"读取文件 {file_path} 失败: {e}")
        
        return files
    
    @staticmethod
    def _get_file_extension(language: str) -> str:
        """获取语言对应的文件扩展名"""
        extensions = {
            'python': 'py',
            'javascript': 'js',
            'typescript': 'ts',
            'java': 'java',
            'c': 'c',
            'cpp': 'cpp',
            'go': 'go',
            'rust': 'rs',
            'ruby': 'rb',
            'php': 'php',
            'html': 'html',
            'css': 'css'
        }
        return extensions.get(language.lower(), 'txt')
    
    @staticmethod
    def _get_file_type(extension: str) -> str:
        """根据扩展名获取文件类型"""
        type_map = {
            '.py': 'Python',
            '.js': 'JavaScript',
            '.ts': 'TypeScript',
            '.java': 'Java',
            '.c': 'C',
            '.cpp': 'C++',
            '.go': 'Go',
            '.rs': 'Rust',
            '.rb': 'Ruby',
            '.php': 'PHP',
            '.html': 'HTML',
            '.css': 'CSS',
            '.json': 'JSON',
            '.md': 'Markdown',
            '.txt': 'Text'
        }
        return type_map.get(extension.lower(), 'Unknown')
    
    @staticmethod
    def _format_file_size(size_bytes: int) -> str:
        """格式化文件大小"""
        for unit in ['B', 'KB', 'MB', 'GB']:
            if size_bytes < 1024.0:
                return f"{size_bytes:.1f} {unit}"
            size_bytes /= 1024.0
        return f"{size_bytes:.1f} TB"
    
    def cleanup(self):
        """清理临时文件"""
        import shutil
        if self.work_dir.exists():
            shutil.rmtree(self.work_dir)


# 简化的 API 接口（用于前端调用）
def process_code_request(request_data: Dict) -> Dict:
    """
    处理代码请求的统一接口
    
    Args:
        request_data: 包含以下字段的字典
            - action: 'generate' | 'edit' | 'explain'
            - prompt: 用户输入
            - language: 编程语言
            - code: (可选) 现有代码
            - files: (可选) 上下文文件
            
    Returns:
        处理结果字典
    """
    action = request_data.get('action', 'generate')
    prompt = request_data.get('prompt', '')
    language = request_data.get('language', 'python')
    
    # 初始化 Aider 服务
    service = AiderService()
    
    try:
        if action == 'generate':
            result = service.generate_code(
                prompt=prompt,
                language=language,
                context_files=request_data.get('files')
            )
        elif action == 'edit':
            file_path = request_data.get('file_path')
            result = service.edit_code(file_path, prompt)
        elif action == 'explain':
            code = request_data.get('code', '')
            result = service.explain_code(code, language)
        else:
            result = {
                'success': False,
                'message': f'不支持的操作: {action}'
            }
        
        return result
        
    finally:
        service.cleanup()


if __name__ == '__main__':
    # 测试示例
    test_request = {
        'action': 'generate',
        'prompt': '创建一个简单的Python函数，用于计算斐波那契数列',
        'language': 'python'
    }
    
    result = process_code_request(test_request)
    print(json.dumps(result, indent=2, ensure_ascii=False))

